[server]
host = "127.0.0.1"
port = 9000

# Redis server config
[redis]
host = "127.0.0.1"
port = 6379
dialread_timeout = 5
dialwrite_timeout = 5
dialconnect_timeout = 5
max_active = 100
max_idle = 50
idle_timeout = 60
